name: Build and Release

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        arch: [ x86_64, arm64 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.os }}
        run: |
          cmake -B build/
          cmake --build build/