/*
** EPITECH PROJECT, 2025
** R-Type
** File description:
** defines
*/

#ifndef DEFINES_HPP_
#define DEFINES_HPP_

#define TIMESTAMP std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count()

#define PROTOCOL_MAGIC 0x5254  // 'RT' in ASCII

#define TIMEOUT_MS 10000
#define HEARTBEAT_INTERVAL 1000
#define ACK_TIMEOUT_MS 1000
#define TICK_RATE 16

#define HEARTBEAT_TICK_INTERVAL 300
#define INPUT_SEND_TICK_INTERVAL 2

#define MAX_PLAYERS 32

// ==============================================================
//              PLAYER SPAWN CONSTANTS
// ==============================================================

#define PLAYER_SPAWN_BASE_X 100.0f
#define PLAYER_SPAWN_HORIZONTAL_SPACING 100.0f
#define PLAYER_SPAWN_BASE_Y 400.0f
#define PLAYER_INITIAL_HEALTH 100
#define PLAYER_IS_PLAYABLE_FLAG_INDEX 15
#define ENTITY_SPAWN_SEQUENCE_BASE 1000

// ==============================================================
//              PLAYER MOVEMENT CONSTANTS
// ==============================================================

#define PLAYER_BASE_SPEED 300.0f  // pixels per second

enum NetworkType {
    NETWORK_TYPE_UNDEFINED = 0,
    NETWORK_TYPE_CLIENT,
    NETWORK_TYPE_SERVER,
    NETWORK_TYPE_STANDALONE
};

// ==============================================================
//              GAME VARIABLE DEFINITIONS
// ==============================================================

// BASE_ENEMY
#define BASE_ENEMY_SPRITE_WIDTH 33
#define BASE_ENEMY_SPRITE_HEIGHT 36
#define BASE_ENEMY_SCALE 1.0f

#define BASE_ENEMY_HEALTH_START 50
#define BASE_ENEMY_HEALTH_MAX 50

#define BASE_ENEMY_VELOCITY_X -20.0f
#define BASE_ENEMY_VELOCITY_Y 0.0f


// base weapon for enemies
#define BASE_ENEMY_WEAPON_DAMAGE 8
#define BASE_ENEMY_WEAPON_FIRE_RATE 800

// ==============================================================
//              ENEMY TYPE DEFINITIONS
// ==============================================================

// FAST ENEMY
#define FAST_ENEMY_HEALTH 30
#define FAST_ENEMY_VELOCITY_X -30.0f
#define FAST_ENEMY_VELOCITY_Y 0.0f
#define FAST_ENEMY_WEAPON_FIRE_RATE 500
#define FAST_ENEMY_WEAPON_DAMAGE 5
#define FAST_ENEMY_SCALE 0.5f

// TANK ENEMY
#define TANK_ENEMY_HEALTH 150
#define TANK_ENEMY_VELOCITY_X -5.0f
#define TANK_ENEMY_VELOCITY_Y 0.0f
#define TANK_ENEMY_WEAPON_FIRE_RATE 1500
#define TANK_ENEMY_WEAPON_DAMAGE 15
#define TANK_ENEMY_SCALE 2.0f

// ==============================================================
//              LEVEL SYSTEM DEFINITIONS
// ==============================================================

// Level 1 Configuration
#define LEVEL_1_NUMBER 1
#define LEVEL_1_DURATION 120.0f  // seconds (0 = infinite/until all waves complete)
#define LEVEL_1_BACKGROUND_ASSET "background_level1"
#define LEVEL_1_MUSIC_ASSET "music_level1"

// Level 1 Wave Timings
#define LEVEL_1_WAVE_1_START_TIME 2.0f
#define LEVEL_1_WAVE_2_START_TIME 10.0f
#define LEVEL_1_WAVE_3_START_TIME 20.0f
#define LEVEL_1_WAVE_4_START_TIME 35.0f

// Level System Background
#define LEVEL_BACKGROUND_SCROLL_SPEED 50.0f

// ==============================================================
//              PACKET SIZE DEFINITIONS (Network Protocol)
// ==============================================================

// Protocol version
#define PROTOCOL_VERSION 1

// Header field sizes
#define HEADER_SIZE 12
#define HEADER_FIELD_MAGIC_SIZE 2
#define HEADER_FIELD_PACKET_TYPE_SIZE 1
#define HEADER_FIELD_FLAGS_SIZE 1
#define HEADER_FIELD_SEQUENCE_NUMBER_SIZE 4
#define HEADER_FIELD_TIMESTAMP_SIZE 4
#define HEADER_FIELD_FLAGS_COUNT_SIZE 1

// ==============================================================
//                    CONNECTION (0x01-0x0F)
// ==============================================================

// CLIENT_CONNECT packet (0x01)
#define CLIENT_CONNECT_PROTOCOL_VERSION_SIZE 1  // uint8_t = PROTOCOL_VERSION
#define CLIENT_CONNECT_PLAYER_NAME_SIZE     32  // char[32]
#define CLIENT_CONNECT_CLIENT_ID_SIZE       4   // uint32_t
#define CLIENT_CONNECT_PAYLOAD_SIZE         (CLIENT_CONNECT_PROTOCOL_VERSION_SIZE + CLIENT_CONNECT_PLAYER_NAME_SIZE + CLIENT_CONNECT_CLIENT_ID_SIZE)  // 37 bytes
#define CLIENT_CONNECT_MIN_ARGS_SIZE        (HEADER_SIZE + CLIENT_CONNECT_PAYLOAD_SIZE)  // 57 bytes

// SERVER_ACCEPT packet (0x02)
#define SERVER_ACCEPT_ASSIGNED_PLAYER_ID_SIZE   4   // uint32_t
#define SERVER_ACCEPT_MAX_PLAYERS_SIZE          1   // uint8_t
#define SERVER_ACCEPT_GAME_INSTANCE_ID_SIZE     4   // uint32_t
#define SERVER_ACCEPT_SERVER_TICKRATE_SIZE      2   // uint16_t
#define SERVER_ACCEPT_PAYLOAD_SIZE              (SERVER_ACCEPT_ASSIGNED_PLAYER_ID_SIZE + SERVER_ACCEPT_MAX_PLAYERS_SIZE + SERVER_ACCEPT_GAME_INSTANCE_ID_SIZE + SERVER_ACCEPT_SERVER_TICKRATE_SIZE)  // 11 bytes
#define SERVER_ACCEPT_MIN_ARGS_SIZE             (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + SERVER_ACCEPT_PAYLOAD_SIZE)  // 23 bytes

// SERVER_REJECT packet (0x03)
#define SERVER_REJECT_REJECT_CODE_SIZE          1   // uint8_t
#define SERVER_REJECT_REASON_MESSAGE_SIZE       64  // char[64]
#define SERVER_REJECT_PAYLOAD_SIZE              (SERVER_REJECT_REJECT_CODE_SIZE + SERVER_REJECT_REASON_MESSAGE_SIZE)  // 65 bytes
#define SERVER_REJECT_MIN_ARGS_SIZE             (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + SERVER_REJECT_PAYLOAD_SIZE)  // 74 bytes (flags_count + seq + ts + payload)

// CLIENT_DISCONNECT packet (0x04)
#define CLIENT_DISCONNECT_PLAYER_ID_SIZE        4   // uint32_t
#define CLIENT_DISCONNECT_REASON_SIZE           1   // uint8_t
#define CLIENT_DISCONNECT_PAYLOAD_SIZE          (CLIENT_DISCONNECT_PLAYER_ID_SIZE + CLIENT_DISCONNECT_REASON_SIZE)  // 5 bytes
#define CLIENT_DISCONNECT_MIN_ARGS_SIZE         (HEADER_SIZE + CLIENT_DISCONNECT_PAYLOAD_SIZE)  // 25 bytes

// HEARTBEAT packet (0x05)
#define HEARTBEAT_PLAYER_ID_SIZE                4   // uint32_t
#define HEARTBEAT_PAYLOAD_SIZE                  (HEARTBEAT_PLAYER_ID_SIZE)  // 4 bytes
#define HEARTBEAT_MIN_ARGS_SIZE                 (HEADER_SIZE + HEARTBEAT_PAYLOAD_SIZE)  // 24 bytes

// ==============================================================
//                    INPUT (0x10-0x1F)
// ==============================================================

// PLAYER_INPUT packet (0x10)
#define PLAYER_INPUT_PLAYER_ID_SIZE             4   // uint32_t
#define PLAYER_INPUT_INPUT_STATE_SIZE           2   // uint16_t
#define PLAYER_INPUT_AIM_DIRECTION_X_SIZE       2   // uint16_t
#define PLAYER_INPUT_AIM_DIRECTION_Y_SIZE       2   // uint16_t
#define PLAYER_INPUT_PAYLOAD_SIZE               (PLAYER_INPUT_PLAYER_ID_SIZE + PLAYER_INPUT_INPUT_STATE_SIZE + PLAYER_INPUT_AIM_DIRECTION_X_SIZE + PLAYER_INPUT_AIM_DIRECTION_Y_SIZE)  // 12 bytes
#define PLAYER_INPUT_MIN_ARGS_SIZE              (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + PLAYER_INPUT_PAYLOAD_SIZE)  // 32 bytes

// PLAYER_IS_READY packet (0x11)
#define PLAYER_READY_PLAYER_ID_SIZE             4   // uint32_t
#define PLAYER_READY_PAYLOAD_SIZE               PLAYER_READY_PLAYER_ID_SIZE  // 4 bytes
#define PLAYER_READY_MIN_ARGS_SIZE              (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + PLAYER_READY_PAYLOAD_SIZE)  // 24 bytes

// ==============================================================
//                    WORLD_STATE (0x20-0x3F)
// ==============================================================

// ENTITY_SPAWN packet (0x21)
#define ENTITY_SPAWN_ENTITY_ID_SIZE             4   // uint32_t
#define ENTITY_SPAWN_ENTITY_TYPE_SIZE           1   // uint8_t
#define ENTITY_SPAWN_POSITION_X_SIZE            2   // uint16_t
#define ENTITY_SPAWN_POSITION_Y_SIZE            2   // uint16_t
#define ENTITY_SPAWN_MOB_VARIANT_SIZE           1   // uint8_t
#define ENTITY_SPAWN_INITIAL_HEALTH_SIZE        1   // uint8_t
#define ENTITY_SPAWN_INITIAL_VELOCITY_X_SIZE    2   // uint16_t
#define ENTITY_SPAWN_INITIAL_VELOCITY_Y_SIZE    2   // uint16_t
#define ENTITY_SPAWN_IS_PLAYABLE_SIZE           1   // uint8_t (0 = no Playable, 1 = has Playable)
#define ENTITY_SPAWN_PAYLOAD_SIZE               (ENTITY_SPAWN_ENTITY_ID_SIZE + ENTITY_SPAWN_ENTITY_TYPE_SIZE + ENTITY_SPAWN_POSITION_X_SIZE + ENTITY_SPAWN_POSITION_Y_SIZE + ENTITY_SPAWN_MOB_VARIANT_SIZE + ENTITY_SPAWN_INITIAL_HEALTH_SIZE + ENTITY_SPAWN_INITIAL_VELOCITY_X_SIZE + ENTITY_SPAWN_INITIAL_VELOCITY_Y_SIZE + ENTITY_SPAWN_IS_PLAYABLE_SIZE)  // 16 bytes
#define ENTITY_SPAWN_MIN_ARGS_SIZE              (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + ENTITY_SPAWN_PAYLOAD_SIZE)  // 36 bytes

// ENTITY_DESTROY packet (0x22)
#define ENTITY_DESTROY_ENTITY_ID_SIZE           4   // uint32_t
#define ENTITY_DESTROY_DESTROY_REASON_SIZE      1   // uint8_t
#define ENTITY_DESTROY_FINAL_POSITION_X_SIZE    2   // uint16_t
#define ENTITY_DESTROY_FINAL_POSITION_Y_SIZE    2   // uint16_t
#define ENTITY_DESTROY_PAYLOAD_SIZE             (ENTITY_DESTROY_ENTITY_ID_SIZE + ENTITY_DESTROY_DESTROY_REASON_SIZE + ENTITY_DESTROY_FINAL_POSITION_X_SIZE + ENTITY_DESTROY_FINAL_POSITION_Y_SIZE)  // 9 bytes
#define ENTITY_DESTROY_MIN_ARGS_SIZE            (HEADER_SIZE + ENTITY_DESTROY_PAYLOAD_SIZE)  // 29 bytes

// ==============================================================
//                    ECS COMPONENTS (0x24-0x2F)
// ==============================================================

// TRANSFORM_SNAPSHOT packet (0x24)
#define TRANSFORM_SNAPSHOT_ENTITY_COUNT_SIZE    2   // uint16_t
#define TRANSFORM_SNAPSHOT_BASE_SIZE            (TRANSFORM_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define TRANSFORM_SNAPSHOT_MIN_ARGS_SIZE        (HEADER_SIZE + TRANSFORM_SNAPSHOT_BASE_SIZE)  // 22 bytes

// VELOCITY_SNAPSHOT packet (0x25)
#define VELOCITY_SNAPSHOT_ENTITY_COUNT_SIZE     2   // uint16_t
#define VELOCITY_SNAPSHOT_BASE_SIZE             (VELOCITY_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define VELOCITY_SNAPSHOT_MIN_ARGS_SIZE         (HEADER_SIZE + VELOCITY_SNAPSHOT_BASE_SIZE)  // 22 bytes

// HEALTH_SNAPSHOT packet (0x26)
#define HEALTH_SNAPSHOT_ENTITY_COUNT_SIZE       2   // uint16_t
#define HEALTH_SNAPSHOT_BASE_SIZE               (HEALTH_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define HEALTH_SNAPSHOT_MIN_ARGS_SIZE           (HEADER_SIZE + HEALTH_SNAPSHOT_BASE_SIZE)  // 22 bytes

// WEAPON_SNAPSHOT packet (0x27)
#define WEAPON_SNAPSHOT_ENTITY_COUNT_SIZE       2   // uint16_t
#define WEAPON_SNAPSHOT_BASE_SIZE               (WEAPON_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define WEAPON_SNAPSHOT_MIN_ARGS_SIZE           (HEADER_SIZE + WEAPON_SNAPSHOT_BASE_SIZE)  // 22 bytes

// AI_SNAPSHOT packet (0x28)
#define AI_SNAPSHOT_ENTITY_COUNT_SIZE           2   // uint16_t
#define AI_SNAPSHOT_BASE_SIZE                   (AI_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define AI_SNAPSHOT_MIN_ARGS_SIZE               (HEADER_SIZE + AI_SNAPSHOT_BASE_SIZE)  // 22 bytes

// ANIMATION_SNAPSHOT packet (0x29)
#define ANIMATION_SNAPSHOT_ENTITY_COUNT_SIZE    2   // uint16_t
#define ANIMATION_SNAPSHOT_BASE_SIZE            (ANIMATION_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define ANIMATION_SNAPSHOT_MIN_ARGS_SIZE        (HEADER_SIZE + ANIMATION_SNAPSHOT_BASE_SIZE)  // 22 bytes

// COMPONENT_ADD packet (0x2A)
#define COMPONENT_ADD_ENTITY_ID_SIZE            4   // uint32_t
#define COMPONENT_ADD_COMPONENT_TYPE_SIZE       1   // uint8_t
#define COMPONENT_ADD_DATA_SIZE_SIZE            1   // uint8_t
#define COMPONENT_ADD_BASE_SIZE                 (COMPONENT_ADD_ENTITY_ID_SIZE + COMPONENT_ADD_COMPONENT_TYPE_SIZE + COMPONENT_ADD_DATA_SIZE_SIZE)  // 6 bytes (+ variable component data)
#define COMPONENT_ADD_MIN_ARGS_SIZE             (HEADER_SIZE + COMPONENT_ADD_BASE_SIZE)  // 26 bytes

// COMPONENT_REMOVE packet (0x2B)
#define COMPONENT_REMOVE_ENTITY_ID_SIZE         4   // uint32_t
#define COMPONENT_REMOVE_COMPONENT_TYPE_SIZE    1   // uint8_t
#define COMPONENT_REMOVE_PAYLOAD_SIZE           (COMPONENT_REMOVE_ENTITY_ID_SIZE + COMPONENT_REMOVE_COMPONENT_TYPE_SIZE)  // 5 bytes
#define COMPONENT_REMOVE_MIN_ARGS_SIZE          (HEADER_SIZE + COMPONENT_REMOVE_PAYLOAD_SIZE)  // 25 bytes

// TRANSFORM_SNAPSHOT_DELTA packet (0x2C)
#define TRANSFORM_SNAPSHOT_DELTA_BASE_TICK_SIZE     4   // uint32_t
#define TRANSFORM_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE  2   // uint16_t
#define TRANSFORM_SNAPSHOT_DELTA_BASE_SIZE          (TRANSFORM_SNAPSHOT_DELTA_BASE_TICK_SIZE + TRANSFORM_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE)  // 6 bytes (+ variable entity data, current tick in header)
#define TRANSFORM_SNAPSHOT_DELTA_MIN_ARGS_SIZE      (HEADER_SIZE + TRANSFORM_SNAPSHOT_DELTA_BASE_SIZE)  // 26 bytes

// HEALTH_SNAPSHOT_DELTA packet (0x2D)
#define HEALTH_SNAPSHOT_DELTA_BASE_TICK_SIZE        4   // uint32_t
#define HEALTH_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE     2   // uint16_t
#define HEALTH_SNAPSHOT_DELTA_BASE_SIZE             (HEALTH_SNAPSHOT_DELTA_BASE_TICK_SIZE + HEALTH_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE)  // 6 bytes (+ variable entity data, current tick in header)
#define HEALTH_SNAPSHOT_DELTA_MIN_ARGS_SIZE         (HEADER_SIZE + HEALTH_SNAPSHOT_DELTA_BASE_SIZE)  // 26 bytes

// ENTITY_FULL_STATE packet (0x2E)
#define ENTITY_FULL_STATE_ENTITY_ID_SIZE        4   // uint32_t
#define ENTITY_FULL_STATE_ENTITY_TYPE_SIZE      1   // uint8_t
#define ENTITY_FULL_STATE_COMPONENT_COUNT_SIZE  1   // uint8_t
#define ENTITY_FULL_STATE_BASE_SIZE             (ENTITY_FULL_STATE_ENTITY_ID_SIZE + ENTITY_FULL_STATE_ENTITY_TYPE_SIZE + ENTITY_FULL_STATE_COMPONENT_COUNT_SIZE)  // 6 bytes (+ variable component data)
#define ENTITY_FULL_STATE_MIN_ARGS_SIZE         (HEADER_SIZE + ENTITY_FULL_STATE_BASE_SIZE)  // 26 bytes

// ==============================================================
//                    GAME_EVENTS (0x40-0x5F)
// ==============================================================

// PLAYER_HIT packet (0x40)
#define PLAYER_HIT_PLAYER_ID_SIZE               4   // uint32_t
#define PLAYER_HIT_ATTACKER_ID_SIZE             4   // uint32_t
#define PLAYER_HIT_DAMAGE_SIZE                  1   // uint8_t
#define PLAYER_HIT_REMAINING_HEALTH_SIZE        1   // uint8_t
#define PLAYER_HIT_REMAINING_SHIELD_SIZE        1   // uint8_t
#define PLAYER_HIT_HIT_POS_X_SIZE               2   // int16_t
#define PLAYER_HIT_HIT_POS_Y_SIZE               2   // int16_t
#define PLAYER_HIT_PAYLOAD_SIZE                 (PLAYER_HIT_PLAYER_ID_SIZE + PLAYER_HIT_ATTACKER_ID_SIZE + PLAYER_HIT_DAMAGE_SIZE + PLAYER_HIT_REMAINING_HEALTH_SIZE + PLAYER_HIT_REMAINING_SHIELD_SIZE + PLAYER_HIT_HIT_POS_X_SIZE + PLAYER_HIT_HIT_POS_Y_SIZE)  // 15 bytes
#define PLAYER_HIT_MIN_ARGS_SIZE                (HEADER_SIZE + PLAYER_HIT_PAYLOAD_SIZE)  // 35 bytes

// PLAYER_DEATH packet (0x41)
#define PLAYER_DEATH_PLAYER_ID_SIZE             4   // uint32_t
#define PLAYER_DEATH_KILLER_ID_SIZE             4   // uint32_t
#define PLAYER_DEATH_SCORE_BEFORE_DEATH_SIZE    4   // uint32_t
#define PLAYER_DEATH_DEATH_POS_X_SIZE           2   // int16_t
#define PLAYER_DEATH_DEATH_POS_Y_SIZE           2   // int16_t
#define PLAYER_DEATH_PAYLOAD_SIZE               (PLAYER_DEATH_PLAYER_ID_SIZE + PLAYER_DEATH_KILLER_ID_SIZE + PLAYER_DEATH_SCORE_BEFORE_DEATH_SIZE + PLAYER_DEATH_DEATH_POS_X_SIZE + PLAYER_DEATH_DEATH_POS_Y_SIZE)  // 16 bytes
#define PLAYER_DEATH_MIN_ARGS_SIZE              (HEADER_SIZE + PLAYER_DEATH_PAYLOAD_SIZE)  // 36 bytes

// SCORE_UPDATE packet (0x42)
#define SCORE_UPDATE_PLAYER_ID_SIZE             4   // uint32_t
#define SCORE_UPDATE_NEW_SCORE_SIZE             4   // uint32_t
#define SCORE_UPDATE_SCORE_DELTA_SIZE           2   // int16_t
#define SCORE_UPDATE_REASON_SIZE                1   // uint8_t
#define SCORE_UPDATE_PAYLOAD_SIZE               (SCORE_UPDATE_PLAYER_ID_SIZE + SCORE_UPDATE_NEW_SCORE_SIZE + SCORE_UPDATE_SCORE_DELTA_SIZE + SCORE_UPDATE_REASON_SIZE)  // 11 bytes
#define SCORE_UPDATE_MIN_ARGS_SIZE              (HEADER_SIZE + SCORE_UPDATE_PAYLOAD_SIZE)  // 31 bytes

// POWER_PICKUP packet (0x43)
#define POWER_PICKUP_PLAYER_ID_SIZE             4   // uint32_t
#define POWER_PICKUP_POWERUP_ID_SIZE            4   // uint32_t
#define POWER_PICKUP_POWERUP_TYPE_SIZE          1   // uint8_t
#define POWER_PICKUP_DURATION_SIZE              1   // uint8_t
#define POWER_PICKUP_PAYLOAD_SIZE               (POWER_PICKUP_PLAYER_ID_SIZE + POWER_PICKUP_POWERUP_ID_SIZE + POWER_PICKUP_POWERUP_TYPE_SIZE + POWER_PICKUP_DURATION_SIZE)  // 10 bytes
#define POWER_PICKUP_MIN_ARGS_SIZE              (HEADER_SIZE + POWER_PICKUP_PAYLOAD_SIZE)  // 30 bytes

// WEAPON_FIRE packet (0x44)
#define WEAPON_FIRE_SHOOTER_ID_SIZE             4   // uint32_t
#define WEAPON_FIRE_PROJECTILE_ID_SIZE          4   // uint32_t
#define WEAPON_FIRE_ORIGIN_X_SIZE               2   // int16_t
#define WEAPON_FIRE_ORIGIN_Y_SIZE               2   // int16_t
#define WEAPON_FIRE_DIRECTION_X_SIZE            2   // int16_t
#define WEAPON_FIRE_DIRECTION_Y_SIZE            2   // int16_t
#define WEAPON_FIRE_WEAPON_TYPE_SIZE            1   // uint8_t
#define WEAPON_FIRE_PAYLOAD_SIZE                (WEAPON_FIRE_SHOOTER_ID_SIZE + WEAPON_FIRE_PROJECTILE_ID_SIZE + WEAPON_FIRE_ORIGIN_X_SIZE + WEAPON_FIRE_ORIGIN_Y_SIZE + WEAPON_FIRE_DIRECTION_X_SIZE + WEAPON_FIRE_DIRECTION_Y_SIZE + WEAPON_FIRE_WEAPON_TYPE_SIZE)  // 17 bytes
// Args format for createWeaponFire: flags_count(1) + flags(1+) + sequence(4) + timestamp(4) + payload(17)
#define WEAPON_FIRE_ARGS_FLAGS_COUNT_SIZE       1   // uint8_t
#define WEAPON_FIRE_ARGS_MIN_FLAGS_SIZE         1   // At least one flag byte
#define WEAPON_FIRE_ARGS_SEQUENCE_SIZE          4   // uint32_t
#define WEAPON_FIRE_ARGS_TIMESTAMP_SIZE         4   // uint32_t
#define WEAPON_FIRE_ARGS_METADATA_SIZE          (WEAPON_FIRE_ARGS_FLAGS_COUNT_SIZE + WEAPON_FIRE_ARGS_MIN_FLAGS_SIZE + WEAPON_FIRE_ARGS_SEQUENCE_SIZE + WEAPON_FIRE_ARGS_TIMESTAMP_SIZE)  // 10 bytes
#define WEAPON_FIRE_MIN_ARGS_SIZE               (WEAPON_FIRE_ARGS_METADATA_SIZE + WEAPON_FIRE_PAYLOAD_SIZE)  // 27 bytes minimum

// VISUAL_EFFECT packet (0x50)
#define VISUAL_EFFECT_EFFECT_TYPE_SIZE          1   // uint8_t
#define VISUAL_EFFECT_POS_X_SIZE                2   // int16_t
#define VISUAL_EFFECT_POS_Y_SIZE                2   // int16_t
#define VISUAL_EFFECT_DURATION_MS_SIZE          2   // uint16_t
#define VISUAL_EFFECT_SCALE_SIZE                1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_R_SIZE         1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_G_SIZE         1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_B_SIZE         1   // uint8_t
#define VISUAL_EFFECT_PAYLOAD_SIZE              (VISUAL_EFFECT_EFFECT_TYPE_SIZE + VISUAL_EFFECT_POS_X_SIZE + VISUAL_EFFECT_POS_Y_SIZE + VISUAL_EFFECT_DURATION_MS_SIZE + VISUAL_EFFECT_SCALE_SIZE + VISUAL_EFFECT_COLOR_TINT_R_SIZE + VISUAL_EFFECT_COLOR_TINT_G_SIZE + VISUAL_EFFECT_COLOR_TINT_B_SIZE)  // 11 bytes
#define VISUAL_EFFECT_MIN_ARGS_SIZE             (HEADER_SIZE + VISUAL_EFFECT_PAYLOAD_SIZE)  // 31 bytes

// AUDIO_EFFECT packet (0x51)
#define AUDIO_EFFECT_EFFECT_TYPE_SIZE           1   // uint8_t
#define AUDIO_EFFECT_POS_X_SIZE                 2   // int16_t
#define AUDIO_EFFECT_POS_Y_SIZE                 2   // int16_t
#define AUDIO_EFFECT_VOLUME_SIZE                1   // uint8_t
#define AUDIO_EFFECT_PITCH_SIZE                 1   // uint8_t
#define AUDIO_EFFECT_PAYLOAD_SIZE               (AUDIO_EFFECT_EFFECT_TYPE_SIZE + AUDIO_EFFECT_POS_X_SIZE + AUDIO_EFFECT_POS_Y_SIZE + AUDIO_EFFECT_VOLUME_SIZE + AUDIO_EFFECT_PITCH_SIZE)  // 7 bytes
#define AUDIO_EFFECT_MIN_ARGS_SIZE              (HEADER_SIZE + AUDIO_EFFECT_PAYLOAD_SIZE)  // 27 bytes

// PARTICLE_SPAWN packet (0x52)
#define PARTICLE_SPAWN_PARTICLE_SYSTEM_ID_SIZE  2   // uint16_t
#define PARTICLE_SPAWN_POS_X_SIZE               2   // int16_t
#define PARTICLE_SPAWN_POS_Y_SIZE               2   // int16_t
#define PARTICLE_SPAWN_VELOCITY_X_SIZE          2   // int16_t
#define PARTICLE_SPAWN_VELOCITY_Y_SIZE          2   // int16_t
#define PARTICLE_SPAWN_PARTICLE_COUNT_SIZE      2   // uint16_t
#define PARTICLE_SPAWN_LIFETIME_MS_SIZE         2   // uint16_t
#define PARTICLE_SPAWN_COLOR_START_R_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_START_G_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_START_B_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_R_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_G_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_B_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_PAYLOAD_SIZE             (PARTICLE_SPAWN_PARTICLE_SYSTEM_ID_SIZE + PARTICLE_SPAWN_POS_X_SIZE + PARTICLE_SPAWN_POS_Y_SIZE + PARTICLE_SPAWN_VELOCITY_X_SIZE + PARTICLE_SPAWN_VELOCITY_Y_SIZE + PARTICLE_SPAWN_PARTICLE_COUNT_SIZE + PARTICLE_SPAWN_LIFETIME_MS_SIZE + PARTICLE_SPAWN_COLOR_START_R_SIZE + PARTICLE_SPAWN_COLOR_START_G_SIZE + PARTICLE_SPAWN_COLOR_START_B_SIZE + PARTICLE_SPAWN_COLOR_END_R_SIZE + PARTICLE_SPAWN_COLOR_END_G_SIZE + PARTICLE_SPAWN_COLOR_END_B_SIZE)  // 20 bytes
#define PARTICLE_SPAWN_MIN_ARGS_SIZE            (HEADER_SIZE + PARTICLE_SPAWN_PAYLOAD_SIZE)  // 40 bytes

// ==============================================================
//                    GAME_CONTROL (0x60-0x6F)
// ==============================================================

// GAME_START packet (0x60)
#define GAME_START_GAME_INSTANCE_ID_SIZE        4   // uint32_t
#define GAME_START_PLAYER_COUNT_SIZE            1   // uint8_t
#define GAME_START_PLAYER_IDS_SIZE              16  // uint32_t[4]
#define GAME_START_LEVEL_ID_SIZE                1   // uint8_t
#define GAME_START_DIFFICULTY_SIZE              1   // uint8_t
#define GAME_START_PAYLOAD_SIZE                 (GAME_START_GAME_INSTANCE_ID_SIZE + GAME_START_PLAYER_COUNT_SIZE + GAME_START_PLAYER_IDS_SIZE + GAME_START_LEVEL_ID_SIZE + GAME_START_DIFFICULTY_SIZE)  // 23 bytes
#define GAME_START_MIN_ARGS_SIZE                (HEADER_SIZE + GAME_START_PAYLOAD_SIZE)  // 43 bytes

// GAME_END packet (0x61)
#define GAME_END_END_REASON_SIZE                1   // uint8_t
#define GAME_END_FINAL_SCORES_SIZE              16  // uint32_t[4]
#define GAME_END_WINNER_ID_SIZE                 1   // uint8_t
#define GAME_END_PLAY_TIME_SIZE                 4   // uint32_t
#define GAME_END_PAYLOAD_SIZE                   (GAME_END_END_REASON_SIZE + GAME_END_FINAL_SCORES_SIZE + GAME_END_WINNER_ID_SIZE + GAME_END_PLAY_TIME_SIZE)  // 22 bytes
#define GAME_END_MIN_ARGS_SIZE                  (HEADER_SIZE + GAME_END_PAYLOAD_SIZE)  // 42 bytes

// LEVEL_COMPLETE packet (0x62)
#define LEVEL_COMPLETE_COMPLETED_LEVEL_SIZE     1   // uint8_t
#define LEVEL_COMPLETE_NEXT_LEVEL_SIZE          1   // uint8_t
#define LEVEL_COMPLETE_BONUS_SCORE_SIZE         4   // uint32_t
#define LEVEL_COMPLETE_COMPLETION_TIME_SIZE     2   // uint16_t
#define LEVEL_COMPLETE_PAYLOAD_SIZE             (LEVEL_COMPLETE_COMPLETED_LEVEL_SIZE + LEVEL_COMPLETE_NEXT_LEVEL_SIZE + LEVEL_COMPLETE_BONUS_SCORE_SIZE + LEVEL_COMPLETE_COMPLETION_TIME_SIZE)  // 8 bytes
#define LEVEL_COMPLETE_MIN_ARGS_SIZE            (HEADER_SIZE + LEVEL_COMPLETE_PAYLOAD_SIZE)  // 28 bytes

// LEVEL_START packet (0x63)
#define LEVEL_START_LEVEL_ID_SIZE               1   // uint8_t
#define LEVEL_START_LEVEL_NAME_SIZE             32  // char[32]
#define LEVEL_START_ESTIMATED_DURATION_SIZE     2   // uint16_t
#define LEVEL_START_PAYLOAD_SIZE                (LEVEL_START_LEVEL_ID_SIZE + LEVEL_START_LEVEL_NAME_SIZE + LEVEL_START_ESTIMATED_DURATION_SIZE)  // 35 bytes
#define LEVEL_START_MIN_ARGS_SIZE               (HEADER_SIZE + LEVEL_START_PAYLOAD_SIZE)  // 55 bytes

// FORCE_STATE packet (0x64)
#define FORCE_STATE_FORCE_ENTITY_ID_SIZE        4   // uint32_t
#define FORCE_STATE_PARENT_SHIP_ID_SIZE         4   // uint32_t
#define FORCE_STATE_ATTACHMENT_POINT_SIZE       1   // uint8_t
#define FORCE_STATE_POWER_LEVEL_SIZE            1   // uint8_t
#define FORCE_STATE_CHARGE_PERCENTAGE_SIZE      1   // uint8_t
#define FORCE_STATE_IS_FIRING_SIZE              1   // uint8_t
#define FORCE_STATE_PAYLOAD_SIZE                (FORCE_STATE_FORCE_ENTITY_ID_SIZE + FORCE_STATE_PARENT_SHIP_ID_SIZE + FORCE_STATE_ATTACHMENT_POINT_SIZE + FORCE_STATE_POWER_LEVEL_SIZE + FORCE_STATE_CHARGE_PERCENTAGE_SIZE + FORCE_STATE_IS_FIRING_SIZE)  // 12 bytes
#define FORCE_STATE_MIN_ARGS_SIZE               (HEADER_SIZE + FORCE_STATE_PAYLOAD_SIZE)  // 32 bytes

// AI_STATE packet (0x65)
#define AI_STATE_ENTITY_ID_SIZE                 4   // uint32_t
#define AI_STATE_CURRENT_STATE_SIZE             1   // uint8_t
#define AI_STATE_BEHAVIOR_TYPE_SIZE             1   // uint8_t
#define AI_STATE_TARGET_ENTITY_ID_SIZE          4   // uint32_t
#define AI_STATE_WAYPOINT_X_SIZE                2   // int16_t
#define AI_STATE_WAYPOINT_Y_SIZE                2   // int16_t
#define AI_STATE_STATE_TIMER_SIZE               2   // uint16_t
#define AI_STATE_PAYLOAD_SIZE                   (AI_STATE_ENTITY_ID_SIZE + AI_STATE_CURRENT_STATE_SIZE + AI_STATE_BEHAVIOR_TYPE_SIZE + AI_STATE_TARGET_ENTITY_ID_SIZE + AI_STATE_WAYPOINT_X_SIZE + AI_STATE_WAYPOINT_Y_SIZE + AI_STATE_STATE_TIMER_SIZE)  // 18 bytes
#define AI_STATE_MIN_ARGS_SIZE                  (HEADER_SIZE + AI_STATE_PAYLOAD_SIZE)  // 38 bytes

// ==============================================================
//                    PROTOCOL_CONTROL (0x70-0x7F)
// ==============================================================

// ACK packet (0x70)
#define ACK_ACKED_SEQUENCE_SIZE                 4   // uint32_t
#define ACK_RECEIVED_TIMESTAMP_SIZE             4   // uint32_t
#define ACK_PAYLOAD_SIZE                        (ACK_ACKED_SEQUENCE_SIZE + ACK_RECEIVED_TIMESTAMP_SIZE)  // 8 bytes
#define ACK_MIN_ARGS_SIZE                       (HEADER_SIZE + ACK_PAYLOAD_SIZE)  // 28 bytes

// PING packet (0x71)
#define PING_CLIENT_TIMESTAMP_SIZE              4   // uint32_t
#define PING_PAYLOAD_SIZE                       (PING_CLIENT_TIMESTAMP_SIZE)  // 4 bytes
#define PING_MIN_ARGS_SIZE                      (HEADER_SIZE + PING_PAYLOAD_SIZE)  // 24 bytes

// PONG packet (0x72)
#define PONG_CLIENT_TIMESTAMP_SIZE              4   // uint32_t
#define PONG_SERVER_TIMESTAMP_SIZE              4   // uint32_t
#define PONG_PAYLOAD_SIZE                       (PONG_CLIENT_TIMESTAMP_SIZE + PONG_SERVER_TIMESTAMP_SIZE)  // 8 bytes
#define PONG_MIN_ARGS_SIZE                      (HEADER_SIZE + PONG_PAYLOAD_SIZE)  // 28 bytes


// ==============================================================
//                          RENDER WINDOW
// ==============================================================

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define FRAMERATE_LIMIT 60

// ================================ GAME ======================================

// =============================== PLAYER =====================================

#define PLAYER_SPRITE_WIDTH 33
#define PLAYER_SPRITE_HEIGHT 15
#define PLAYER_SPRITE_SCALE 2.5f

#define PLAYER_ANIMATION_WIDTH 33
#define PLAYER_ANIMATION_HEIGHT 15
#define PLAYER_ANIMATION_CURRENT 2
#define PLAYER_ANIMATION_ELAPSED_TIME 0.f
#define PLAYER_ANIMATION_DURATION 0.1f
#define PLAYER_ANIMATION_START 2
#define PLAYER_ANIMATION_END 2
#define PLAYER_ANIMATION_LOOPING true

#define PLAYER_WEAPON_FIRE_RATE = 200
#define PLAYER_WEAPON_LAST_SHOT = 0
#define PLAYER_WEAPON_DAMAGES = 10
#define PLAYER_WEAPON_TYPE = ProjectileType::MISSILE


// =============================== EXPLOSIONS ================================

// SMALL EXPLOSIONS
#define SMALL_EXPLOSION_SPRITE_WIDTH 33
#define SMALL_EXPLOSION_SPRITE_HEIGHT 32
#define SMALL_EXPLOSION_SPRITE_SCALE 2.5f

#define SMALL_EXPLOSION_ANIMATION_WIDTH 33
#define SMALL_EXPLOSION_ANIMATION_HEIGHT 32
#define SMALL_EXPLOSION_ANIMATION_CURRENT 0
#define SMALL_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define SMALL_EXPLOSION_ANIMATION_DURATION 0.1f
#define SMALL_EXPLOSION_ANIMATION_START 0
#define SMALL_EXPLOSION_ANIMATION_END 5
#define SMALL_EXPLOSION_ANIMATION_LOOPING false

// MEDIUM EXPLOSIONS
#define MEDIUM_EXPLOSION_SPRITE_WIDTH 60
#define MEDIUM_EXPLOSION_SPRITE_HEIGHT 52
#define MEDIUM_EXPLOSION_SPRITE_SCALE 2.5f

#define MEDIUM_EXPLOSION_ANIMATION_WIDTH 60
#define MEDIUM_EXPLOSION_ANIMATION_HEIGHT 52
#define MEDIUM_EXPLOSION_ANIMATION_CURRENT 0
#define MEDIUM_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define MEDIUM_EXPLOSION_ANIMATION_DURATION 0.1f
#define MEDIUM_EXPLOSION_ANIMATION_START 0
#define MEDIUM_EXPLOSION_ANIMATION_END 2
#define MEDIUM_EXPLOSION_ANIMATION_LOOPING false

// BIG EXPLOSIONS
#define BIG_EXPLOSION_SPRITE_WIDTH 65
#define BIG_EXPLOSION_SPRITE_HEIGHT 65
#define BIG_EXPLOSION_SPRITE_SCALE 2.5f

#define BIG_EXPLOSION_ANIMATION_WIDTH 65
#define BIG_EXPLOSION_ANIMATION_HEIGHT 65
#define BIG_EXPLOSION_ANIMATION_CURRENT 0
#define BIG_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define BIG_EXPLOSION_ANIMATION_DURATION 0.1f
#define BIG_EXPLOSION_ANIMATION_START 0
#define BIG_EXPLOSION_ANIMATION_END 4
#define BIG_EXPLOSION_ANIMATION_LOOPING false


// =============================== BULLETS ================================

// BASIC/DEFAULT BULLET
#define DEFAULT_BULLET_ROTATION 0
#define DEFAULT_BULLET_SCALE 2.5f

#define DEFAULT_BULLET_SPRITE_WIDTH 17
#define DEFAULT_BULLET_SPRITE_HEIGHT 12
#define DEFAULT_BULLET_SPRITE_SCALE 2.5f

#define DEFAULT_BULLET_ANIMATION_WIDTH 17
#define DEFAULT_BULLET_ANIMATION_HEIGHT 12
#define DEFAULT_BULLET_ANIMATION_CURRENT 0
#define DEFAULT_BULLET_ANIMATION_ELAPSED_TIME 0.f
#define DEFAULT_BULLET_ANIMATION_DURATION 0.1f
#define DEFAULT_BULLET_ANIMATION_START 0
#define DEFAULT_BULLET_ANIMATION_END 2
#define DEFAULT_BULLET_ANIMATION_LOOPING false


// CHARGED BULLET
#define CHARGED_BULLET_ROTATION 0
#define CHARGED_BULLET_SCALE 2.5f

#define CHARGED_BULLET_SPRITE_WIDTH 81
#define CHARGED_BULLET_SPRITE_HEIGHT 16
#define CHARGED_BULLET_SPRITE_SCALE 2.5f

#define CHARGED_BULLET_ANIMATION_WIDTH 81
#define CHARGED_BULLET_ANIMATION_HEIGHT 16
#define CHARGED_BULLET_ANIMATION_CURRENT 0
#define CHARGED_BULLET_ANIMATION_ELAPSED_TIME 0.f
#define CHARGED_BULLET_ANIMATION_DURATION 0.3f
#define CHARGED_BULLET_ANIMATION_START 0
#define CHARGED_BULLET_ANIMATION_END 1
#define CHARGED_BULLET_ANIMATION_LOOPING true // verify if its better to set to true ou false for this bullets

// SPIRAL BULLET
#define SPIRAL_BULLET_ROTATION 0
#define SPIRAL_BULLET_SCALE 2.5f

#define SPIRAL_BULLET_SPRITE_WIDTH 34
#define SPIRAL_BULLET_SPRITE_HEIGHT 34
#define SPIRAL_BULLET_SPRITE_SCALE 2.5f

#define SPIRAL_BULLET_ANIMATION_WIDTH 34
#define SPIRAL_BULLET_ANIMATION_HEIGHT 34
#define SPIRAL_BULLET_ANIMATION_CURRENT 0
#define SPIRAL_BULLET_ANIMATION_ELAPSED_TIME 0.f
#define SPIRAL_BULLET_ANIMATION_DURATION 0.15f
#define SPIRAL_BULLET_ANIMATION_START 0
#define SPIRAL_BULLET_ANIMATION_END 2
#define SPIRAL_BULLET_ANIMATION_LOOPING true // verify if its better to set to true ou false for this bullets
// =============================== PROJECTILES ================================

// BULLET SPEED (units per millisecond)
#define BULLET_SPEED 1000.0f


// =============================== ENEMIES ====================================

//TODO: set defines for each enemies assets!

// BASE ENEMY

//FIXME: not the correct one, fix it (ya plus de co à epitech ptn)
// #define BASE_ENEMY_SPRITE_WIDTH 225
// #define BASE_ENEMY_SPRITE_HEIGHT 225
// #define BASE_ENEMY_SPRITE_SCALE 1.0f // maybe need to be changed

// #define BASE_ENEMY_ANIMATION_WIDTH 225
// #define BASE_ENEMY_ANIMATION_HEIGHT 225
// #define BASE_ENEMY_ANIMATION_CURRENT 0
// #define BASE_ENEMY_ANIMATION_ELAPSED_TIME 0.f
// #define BASE_ENEMY_ANIMATION_DURATION 0.1f
// #define BASE_ENEMY_ANIMATION_START 0
// #define BASE_ENEMY_ANIMATION_END 49
// #define BASE_ENEMY_ANIMATION_LOOPING true


// BASE WALKER ENEMY

//FIXME: not the correct one, fix it (ya plus de co à epitech ptn)
// #define BASE_WALKER_ENEMY_SPRITE_WIDTH 225
// #define BASE_WALKER_ENEMY_SPRITE_HEIGHT 225
// #define BASE_WALKER_ENEMY_SPRITE_SCALE 1.0f // maybe need to be changed

// #define BASE_WALKER_ENEMY_ANIMATION_WIDTH 225
// #define BASE_WALKER_ENEMY_ANIMATION_HEIGHT 225
// #define BASE_WALKER_ENEMY_ANIMATION_CURRENT 0
// #define BASE_WALKER_ENEMY_ANIMATION_ELAPSED_TIME 0.f
// #define BASE_WALKER_ENEMY_ANIMATION_DURATION 0.1f
// #define BASE_WALKER_ENEMY_ANIMATION_START 0
// #define BASE_WALKER_ENEMY_ANIMATION_END 49
// #define BASE_WALKER_ENEMY_ANIMATION_LOOPING true

// GREEN BRAIN ENEMY

//FIXME: not the correct one, fix it (ya plus de co à epitech ptn)
// #define GREEN_BRAIN_ENEMY_SPRITE_WIDTH 225
// #define GREEN_BRAIN_ENEMY_SPRITE_HEIGHT 225
// #define GREEN_BRAIN_ENEMY_SPRITE_SCALE 1.0f // maybe need to be changed

// #define GREEN_BRAIN_ENEMY_ANIMATION_WIDTH 225
// #define GREEN_BRAIN_ENEMY_ANIMATION_HEIGHT 225
// #define GREEN_BRAIN_ENEMY_ANIMATION_CURRENT 0
// #define GREEN_BRAIN_ENEMY_ANIMATION_ELAPSED_TIME 0.f
// #define GREEN_BRAIN_ENEMY_ANIMATION_DURATION 0.1f
// #define GREEN_BRAIN_ENEMY_ANIMATION_START 0
// #define GREEN_BRAIN_ENEMY_ANIMATION_END 49
// #define GREEN_BRAIN_ENEMY_ANIMATION_LOOPING true

// TURBINE ENEMY

//FIXME: not the correct one, fix it (ya plus de co à epitech ptn)
// #define TURBINE_ENEMY_SPRITE_WIDTH 225
// #define TURBINE_ENEMY_SPRITE_HEIGHT 225
// #define TURBINE_ENEMY_SPRITE_SCALE 1.0f // maybe need to be changed

// #define TURBINE_ENEMY_ANIMATION_WIDTH 225
// #define TURBINE_ENEMY_ANIMATION_HEIGHT 225
// #define TURBINE_ENEMY_ANIMATION_CURRENT 0
// #define TURBINE_ENEMY_ANIMATION_ELAPSED_TIME 0.f
// #define TURBINE_ENEMY_ANIMATION_DURATION 0.1f
// #define TURBINE_ENEMY_ANIMATION_START 0
// #define TURBINE_ENEMY_ANIMATION_END 49
// #define TURBINE_ENEMY_ANIMATION_LOOPING true


// ================================ BOSS ======================================

// GREEN CELLS ENEMY

//FIXME: not the correct one, fix it (ya plus de co à epitech ptn)
// #define GREEN_CELLS_BOSS_SPRITE_WIDTH 225
// #define GREEN_CELLS_BOSS_SPRITE_HEIGHT 225
// #define GREEN_CELLS_BOSS_SPRITE_SCALE 1.0f

// #define GREEN_CELLS_BOSS_ANIMATION_WIDTH 225
// #define GREEN_CELLS_BOSS_ANIMATION_HEIGHT 225
// #define GREEN_CELLS_BOSS_ANIMATION_CURRENT 0
// #define GREEN_CELLS_BOSS_ANIMATION_ELAPSED_TIME 0.f
// #define GREEN_CELLS_BOSS_ANIMATION_DURATION 0.1f
// #define GREEN_CELLS_BOSS_ANIMATION_START 0
// #define GREEN_CELLS_BOSS_ANIMATION_END 49
// #define GREEN_CELLS_BOSS_ANIMATION_LOOPING true

// SPACESHIP ENEMY
#define SPACESHIP_MENU_SPRITE_WIDTH 130
#define SPACESHIP_MENU_SPRITE_HEIGHT 50
#define SPACESHIP_MENU_SPRITE_SCALE 2.5f // maybe need to be changed


// =============================== POWERUPS ===================================

// PET POWERUP
#define PET_POWERUP_SPRITE_WIDTH 17
#define PET_POWERUP_SPRITE_HEIGHT 14
#define PET_POWERUP_SPRITE_SCALE 2.5f // maybe need to be changed

#define PET_POWERUP_ANIMATION_WIDTH 17
#define PET_POWERUP_ANIMATION_HEIGHT 14
#define PET_POWERUP_ANIMATION_CURRENT 0
#define PET_POWERUP_ANIMATION_ELAPSED_TIME 0.f
#define PET_POWERUP_ANIMATION_DURATION 0.1f
#define PET_POWERUP_ANIMATION_START 0
#define PET_POWERUP_ANIMATION_END 11
#define PET_POWERUP_ANIMATION_LOOPING true

// =========================== GAME BACKGROUNDS ===============================

// GAME BACKGROUND
#define GAME_BG_ROTATION 0
#define GAME_BG_SCALE 1.0f
#define GAME_BG_SPRITE_WIDTH 1920
#define GAME_BG_SPRITE_HEIGHT 1080



// =============================== UI/HUD =====================================

// =============================== BUTTONS ====================================
// DEFAULT BUTTON
#define DEFAULT_BUTTON_ROTATION 0
#define DEFAULT_BUTTON_SCALE 1.5f
#define DEFAULT_BUTTON_MID_SCALE 1.0f
#define DEFAULT_BUTTON_LITTLE_SCALE 0.5f
#define DEFAULT_BUTTON_SPRITE_WIDTH 280
#define DEFAULT_BUTTON_SPRITE_HEIGHT 80


// BACK BUTTON
#define BACK_BUTTON_ROTATION 0
#define BACK_BUTTON_SCALE 3.5f //FIXME: need to be changed I think
#define BACK_BUTTON_SPRITE_WIDTH 22
#define BACK_BUTTON_SPRITE_HEIGHT 20


// MUSIC BUTTON
#define MUSIC_BUTTON_ROTATION 0
#define MUSIC_BUTTON_SCALE 8.0f //FIXME: need to be changed I think
#define MUSIC_BUTTON_SPRITE_WIDTH 16
#define MUSIC_BUTTON_SPRITE_HEIGHT 14

// SOUND BUTTON
#define SOUND_BUTTON_ROTATION 0
#define SOUND_BUTTON_SCALE 8.0f //FIXME: need to be changed I think
#define SOUND_BUTTON_SPRITE_WIDTH 16
#define SOUND_BUTTON_SPRITE_HEIGHT 14

// ================================ MENUS =====================================

// ============================== MAIN MENU ===================================

// LOGO
#define LOGO_RTYPE_ROTATION 0
#define LOGO_RTYPE_SCALE 1.4f // maybe need to be changed
#define LOGO_RTYPE_SPRITE_WIDTH 500
#define LOGO_RTYPE_SPRITE_HEIGHT 146


// MAIN_MENU BACKGROUND
#define MAIN_MENU_BG_ROTATION 0
#define MAIN_MENU_BG_SCALE 1.0f
#define MAIN_MENU_BG_SPRITE_WIDTH 1920
#define MAIN_MENU_BG_SPRITE_HEIGHT 1080


// MAIN_MENU BACKGROUND
#define MAIN_MENU_PLANET_SPRITE_WIDTH 225
#define MAIN_MENU_PLANET_SPRITE_HEIGHT 225
#define MAIN_MENU_PLANET_SPRITE_SCALE 16.0f // maybe need to be changed
// #define MAIN_MENU_PLANET_SPRITE_SCALE 8.0f // maybe need to be changed


#define MAIN_MENU_PLANET_ANIMATION_WIDTH 225
#define MAIN_MENU_PLANET_ANIMATION_HEIGHT 225
#define MAIN_MENU_PLANET_ANIMATION_CURRENT 0
#define MAIN_MENU_PLANET_ANIMATION_ELAPSED_TIME 0.f
#define MAIN_MENU_PLANET_ANIMATION_DURATION 0.15f
#define MAIN_MENU_PLANET_ANIMATION_START 0
#define MAIN_MENU_PLANET_ANIMATION_END 49
#define MAIN_MENU_PLANET_ANIMATION_LOOPING true



// =========================== OPTIONS MENU ===================================

// OPTION_MENU BACKGROUND
#define OPTION_MENU_BG_ROTATION 0
#define OPTION_MENU_BG_SCALE 1.0f
#define OPTION_MENU_BG_SPRITE_WIDTH 1920
#define OPTION_MENU_BG_SPRITE_HEIGHT 1080


// OPTION_MENU BACKGROUND
#define OPTION_MENU_PLANET_SPRITE_WIDTH 225
#define OPTION_MENU_PLANET_SPRITE_HEIGHT 225
#define OPTION_MENU_PLANET_SPRITE_SCALE 16.0f // maybe need to be changed
// #define OPTION_MENU_PLANET_SPRITE_SCALE 8.0f // maybe need to be changed


#define OPTION_MENU_PLANET_ANIMATION_WIDTH 225
#define OPTION_MENU_PLANET_ANIMATION_HEIGHT 225
#define OPTION_MENU_PLANET_ANIMATION_CURRENT 0
#define OPTION_MENU_PLANET_ANIMATION_ELAPSED_TIME 0.f
#define OPTION_MENU_PLANET_ANIMATION_DURATION 0.15f
#define OPTION_MENU_PLANET_ANIMATION_START 0
#define OPTION_MENU_PLANET_ANIMATION_END 49
#define OPTION_MENU_PLANET_ANIMATION_LOOPING true

// ==============================================================
//                        AUDIO SYSTEM
// ==============================================================

// Audio source default parameters
#define AUDIO_SOURCE_DEFAULT_LOOP false
#define AUDIO_SOURCE_DEFAULT_MIN_DISTANCE 100.0f
#define AUDIO_SOURCE_DEFAULT_ATTENUATION 0.5f
#define AUDIO_SOURCE_DEFAULT_IS_UI false
#define AUDIO_SOURCE_DEFAULT_PLAY_ONCE true
#define AUDIO_SOURCE_DEFAULT_DURATION 1.0f

// Weapon sound durations (in seconds)
#define AUDIO_SHOOT_BASIC_DURATION 0.3f
#define AUDIO_SHOOT_CHARGED_DURATION 0.4f
#define AUDIO_SHOOT_LASER_DURATION 0.35f

// Explosion sound durations
#define AUDIO_EXPLOSION_SMALL_DURATION 0.5f
#define AUDIO_EXPLOSION_LARGE_DURATION 0.7f

// Projectile audio parameters (weapon-specific)
#define AUDIO_BASIC_PROJECTILE_LOOP false
#define AUDIO_BASIC_PROJECTILE_MIN_DISTANCE 100.0f
#define AUDIO_BASIC_PROJECTILE_ATTENUATION 0.5f

#define AUDIO_CHARGED_PROJECTILE_LOOP false
#define AUDIO_CHARGED_PROJECTILE_MIN_DISTANCE 150.0f
#define AUDIO_CHARGED_PROJECTILE_ATTENUATION 0.3f

#define AUDIO_LASER_PROJECTILE_LOOP false
#define AUDIO_LASER_PROJECTILE_MIN_DISTANCE 120.0f
#define AUDIO_LASER_PROJECTILE_ATTENUATION 0.4f

#endif /* !DEFINES_HPP_ */