/*
** EPITECH PROJECT, 2025
** R-Type
** File description:
** defines
*/

#ifndef DEFINES_HPP_
#define DEFINES_HPP_

#define TIMESTAMP std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count()

#define PROTOCOL_MAGIC 0x5254  // 'RT' in ASCII

#define TIMEOUT_MS 10000
#define HEARTBEAT_INTERVAL 1000
#define ACK_TIMEOUT_MS 1000
#define TICK_RATE 16

#define HEARTBEAT_TICK_INTERVAL 300
#define INPUT_SEND_TICK_INTERVAL 2

#define MAX_PLAYERS 32

enum NetworkType {
    NETWORK_TYPE_UNDEFINED = 0,
    NETWORK_TYPE_CLIENT,
    NETWORK_TYPE_SERVER,
    NETWORK_TYPE_STANDALONE
};

// ==============================================================
//              GAME VARIABLE DEFINITIONS
// ==============================================================

// BASE_ENEMY
#define BASE_ENEMY_SPRITE_WIDTH 33
#define BASE_ENEMY_SPRITE_HEIGHT 36

#define BASE_ENEMY_HEALTH_START 50
#define BASE_ENEMY_HEALTH_MAX 50

#define BASE_ENEMY_VELOCITY_X 0.0f
#define BASE_ENEMY_VELOCITY_Y 0.0f


// base weapon for enemies
#define BASE_ENEMY_WEAPON_DAMAGE 8
#define BASE_ENEMY_WEAPON_FIRE_RATE 300

// ==============================================================
//              PACKET SIZE DEFINITIONS (Network Protocol)
// ==============================================================

// Protocol version
#define PROTOCOL_VERSION 1

// Header field sizes
#define HEADER_SIZE 12
#define HEADER_FIELD_MAGIC_SIZE 2
#define HEADER_FIELD_PACKET_TYPE_SIZE 1
#define HEADER_FIELD_FLAGS_SIZE 1
#define HEADER_FIELD_SEQUENCE_NUMBER_SIZE 4
#define HEADER_FIELD_TIMESTAMP_SIZE 4
#define HEADER_FIELD_FLAGS_COUNT_SIZE 1

// ==============================================================
//                    CONNECTION (0x01-0x0F)
// ==============================================================

// CLIENT_CONNECT packet (0x01)
#define CLIENT_CONNECT_PROTOCOL_VERSION_SIZE 1  // uint8_t = PROTOCOL_VERSION
#define CLIENT_CONNECT_PLAYER_NAME_SIZE     32  // char[32]
#define CLIENT_CONNECT_CLIENT_ID_SIZE       4   // uint32_t
#define CLIENT_CONNECT_PAYLOAD_SIZE         (CLIENT_CONNECT_PROTOCOL_VERSION_SIZE + CLIENT_CONNECT_PLAYER_NAME_SIZE + CLIENT_CONNECT_CLIENT_ID_SIZE)  // 37 bytes
#define CLIENT_CONNECT_MIN_ARGS_SIZE        (HEADER_SIZE + CLIENT_CONNECT_PAYLOAD_SIZE)  // 57 bytes

// SERVER_ACCEPT packet (0x02)
#define SERVER_ACCEPT_ASSIGNED_PLAYER_ID_SIZE   4   // uint32_t
#define SERVER_ACCEPT_MAX_PLAYERS_SIZE          1   // uint8_t
#define SERVER_ACCEPT_GAME_INSTANCE_ID_SIZE     4   // uint32_t
#define SERVER_ACCEPT_SERVER_TICKRATE_SIZE      2   // uint16_t
#define SERVER_ACCEPT_PAYLOAD_SIZE              (SERVER_ACCEPT_ASSIGNED_PLAYER_ID_SIZE + SERVER_ACCEPT_MAX_PLAYERS_SIZE + SERVER_ACCEPT_GAME_INSTANCE_ID_SIZE + SERVER_ACCEPT_SERVER_TICKRATE_SIZE)  // 11 bytes
#define SERVER_ACCEPT_MIN_ARGS_SIZE             (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + SERVER_ACCEPT_PAYLOAD_SIZE)  // 23 bytes

// SERVER_REJECT packet (0x03)
#define SERVER_REJECT_REJECT_CODE_SIZE          1   // uint8_t
#define SERVER_REJECT_REASON_MESSAGE_SIZE       64  // char[64]
#define SERVER_REJECT_PAYLOAD_SIZE              (SERVER_REJECT_REJECT_CODE_SIZE + SERVER_REJECT_REASON_MESSAGE_SIZE)  // 65 bytes
#define SERVER_REJECT_MIN_ARGS_SIZE             (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + SERVER_REJECT_PAYLOAD_SIZE)  // 74 bytes (flags_count + seq + ts + payload)

// CLIENT_DISCONNECT packet (0x04)
#define CLIENT_DISCONNECT_PLAYER_ID_SIZE        4   // uint32_t
#define CLIENT_DISCONNECT_REASON_SIZE           1   // uint8_t
#define CLIENT_DISCONNECT_PAYLOAD_SIZE          (CLIENT_DISCONNECT_PLAYER_ID_SIZE + CLIENT_DISCONNECT_REASON_SIZE)  // 5 bytes
#define CLIENT_DISCONNECT_MIN_ARGS_SIZE         (HEADER_SIZE + CLIENT_DISCONNECT_PAYLOAD_SIZE)  // 25 bytes

// HEARTBEAT packet (0x05)
#define HEARTBEAT_PLAYER_ID_SIZE                4   // uint32_t
#define HEARTBEAT_PAYLOAD_SIZE                  (HEARTBEAT_PLAYER_ID_SIZE)  // 4 bytes
#define HEARTBEAT_MIN_ARGS_SIZE                 (HEADER_SIZE + HEARTBEAT_PAYLOAD_SIZE)  // 24 bytes

// ==============================================================
//                    INPUT (0x10-0x1F)
// ==============================================================

// PLAYER_INPUT packet (0x10)
#define PLAYER_INPUT_PLAYER_ID_SIZE             4   // uint32_t
#define PLAYER_INPUT_INPUT_STATE_SIZE           2   // uint16_t
#define PLAYER_INPUT_AIM_DIRECTION_X_SIZE       2   // uint16_t
#define PLAYER_INPUT_AIM_DIRECTION_Y_SIZE       2   // uint16_t
#define PLAYER_INPUT_PAYLOAD_SIZE               (PLAYER_INPUT_PLAYER_ID_SIZE + PLAYER_INPUT_INPUT_STATE_SIZE + PLAYER_INPUT_AIM_DIRECTION_X_SIZE + PLAYER_INPUT_AIM_DIRECTION_Y_SIZE)  // 12 bytes
#define PLAYER_INPUT_MIN_ARGS_SIZE              (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + PLAYER_INPUT_PAYLOAD_SIZE)  // 32 bytes

// ==============================================================
//                    WORLD_STATE (0x20-0x3F)
// ==============================================================

// ENTITY_SPAWN packet (0x21)
#define ENTITY_SPAWN_ENTITY_ID_SIZE             4   // uint32_t
#define ENTITY_SPAWN_ENTITY_TYPE_SIZE           1   // uint8_t
#define ENTITY_SPAWN_POSITION_X_SIZE            2   // uint16_t
#define ENTITY_SPAWN_POSITION_Y_SIZE            2   // uint16_t
#define ENTITY_SPAWN_MOB_VARIANT_SIZE           1   // uint8_t
#define ENTITY_SPAWN_INITIAL_HEALTH_SIZE        1   // uint8_t
#define ENTITY_SPAWN_INITIAL_VELOCITY_X_SIZE    2   // uint16_t
#define ENTITY_SPAWN_INITIAL_VELOCITY_Y_SIZE    2   // uint16_t
#define ENTITY_SPAWN_IS_PLAYABLE_SIZE           1   // uint8_t (0 = no Playable, 1 = has Playable)
#define ENTITY_SPAWN_PAYLOAD_SIZE               (ENTITY_SPAWN_ENTITY_ID_SIZE + ENTITY_SPAWN_ENTITY_TYPE_SIZE + ENTITY_SPAWN_POSITION_X_SIZE + ENTITY_SPAWN_POSITION_Y_SIZE + ENTITY_SPAWN_MOB_VARIANT_SIZE + ENTITY_SPAWN_INITIAL_HEALTH_SIZE + ENTITY_SPAWN_INITIAL_VELOCITY_X_SIZE + ENTITY_SPAWN_INITIAL_VELOCITY_Y_SIZE + ENTITY_SPAWN_IS_PLAYABLE_SIZE)  // 16 bytes
#define ENTITY_SPAWN_MIN_ARGS_SIZE              (HEADER_FIELD_FLAGS_COUNT_SIZE + HEADER_FIELD_SEQUENCE_NUMBER_SIZE + HEADER_FIELD_TIMESTAMP_SIZE + ENTITY_SPAWN_PAYLOAD_SIZE)  // 36 bytes

// ENTITY_DESTROY packet (0x22)
#define ENTITY_DESTROY_ENTITY_ID_SIZE           4   // uint32_t
#define ENTITY_DESTROY_DESTROY_REASON_SIZE      1   // uint8_t
#define ENTITY_DESTROY_FINAL_POSITION_X_SIZE    2   // uint16_t
#define ENTITY_DESTROY_FINAL_POSITION_Y_SIZE    2   // uint16_t
#define ENTITY_DESTROY_PAYLOAD_SIZE             (ENTITY_DESTROY_ENTITY_ID_SIZE + ENTITY_DESTROY_DESTROY_REASON_SIZE + ENTITY_DESTROY_FINAL_POSITION_X_SIZE + ENTITY_DESTROY_FINAL_POSITION_Y_SIZE)  // 9 bytes
#define ENTITY_DESTROY_MIN_ARGS_SIZE            (HEADER_SIZE + ENTITY_DESTROY_PAYLOAD_SIZE)  // 29 bytes

// ==============================================================
//                    ECS COMPONENTS (0x24-0x2F)
// ==============================================================

// TRANSFORM_SNAPSHOT packet (0x24)
#define TRANSFORM_SNAPSHOT_ENTITY_COUNT_SIZE    2   // uint16_t
#define TRANSFORM_SNAPSHOT_BASE_SIZE            (TRANSFORM_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define TRANSFORM_SNAPSHOT_MIN_ARGS_SIZE        (HEADER_SIZE + TRANSFORM_SNAPSHOT_BASE_SIZE)  // 22 bytes

// VELOCITY_SNAPSHOT packet (0x25)
#define VELOCITY_SNAPSHOT_ENTITY_COUNT_SIZE     2   // uint16_t
#define VELOCITY_SNAPSHOT_BASE_SIZE             (VELOCITY_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define VELOCITY_SNAPSHOT_MIN_ARGS_SIZE         (HEADER_SIZE + VELOCITY_SNAPSHOT_BASE_SIZE)  // 22 bytes

// HEALTH_SNAPSHOT packet (0x26)
#define HEALTH_SNAPSHOT_ENTITY_COUNT_SIZE       2   // uint16_t
#define HEALTH_SNAPSHOT_BASE_SIZE               (HEALTH_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define HEALTH_SNAPSHOT_MIN_ARGS_SIZE           (HEADER_SIZE + HEALTH_SNAPSHOT_BASE_SIZE)  // 22 bytes

// WEAPON_SNAPSHOT packet (0x27)
#define WEAPON_SNAPSHOT_ENTITY_COUNT_SIZE       2   // uint16_t
#define WEAPON_SNAPSHOT_BASE_SIZE               (WEAPON_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define WEAPON_SNAPSHOT_MIN_ARGS_SIZE           (HEADER_SIZE + WEAPON_SNAPSHOT_BASE_SIZE)  // 22 bytes

// AI_SNAPSHOT packet (0x28)
#define AI_SNAPSHOT_ENTITY_COUNT_SIZE           2   // uint16_t
#define AI_SNAPSHOT_BASE_SIZE                   (AI_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define AI_SNAPSHOT_MIN_ARGS_SIZE               (HEADER_SIZE + AI_SNAPSHOT_BASE_SIZE)  // 22 bytes

// ANIMATION_SNAPSHOT packet (0x29)
#define ANIMATION_SNAPSHOT_ENTITY_COUNT_SIZE    2   // uint16_t
#define ANIMATION_SNAPSHOT_BASE_SIZE            (ANIMATION_SNAPSHOT_ENTITY_COUNT_SIZE)  // 2 bytes (+ variable entity data, tick in header)
#define ANIMATION_SNAPSHOT_MIN_ARGS_SIZE        (HEADER_SIZE + ANIMATION_SNAPSHOT_BASE_SIZE)  // 22 bytes

// COMPONENT_ADD packet (0x2A)
#define COMPONENT_ADD_ENTITY_ID_SIZE            4   // uint32_t
#define COMPONENT_ADD_COMPONENT_TYPE_SIZE       1   // uint8_t
#define COMPONENT_ADD_DATA_SIZE_SIZE            1   // uint8_t
#define COMPONENT_ADD_BASE_SIZE                 (COMPONENT_ADD_ENTITY_ID_SIZE + COMPONENT_ADD_COMPONENT_TYPE_SIZE + COMPONENT_ADD_DATA_SIZE_SIZE)  // 6 bytes (+ variable component data)
#define COMPONENT_ADD_MIN_ARGS_SIZE             (HEADER_SIZE + COMPONENT_ADD_BASE_SIZE)  // 26 bytes

// COMPONENT_REMOVE packet (0x2B)
#define COMPONENT_REMOVE_ENTITY_ID_SIZE         4   // uint32_t
#define COMPONENT_REMOVE_COMPONENT_TYPE_SIZE    1   // uint8_t
#define COMPONENT_REMOVE_PAYLOAD_SIZE           (COMPONENT_REMOVE_ENTITY_ID_SIZE + COMPONENT_REMOVE_COMPONENT_TYPE_SIZE)  // 5 bytes
#define COMPONENT_REMOVE_MIN_ARGS_SIZE          (HEADER_SIZE + COMPONENT_REMOVE_PAYLOAD_SIZE)  // 25 bytes

// TRANSFORM_SNAPSHOT_DELTA packet (0x2C)
#define TRANSFORM_SNAPSHOT_DELTA_BASE_TICK_SIZE     4   // uint32_t
#define TRANSFORM_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE  2   // uint16_t
#define TRANSFORM_SNAPSHOT_DELTA_BASE_SIZE          (TRANSFORM_SNAPSHOT_DELTA_BASE_TICK_SIZE + TRANSFORM_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE)  // 6 bytes (+ variable entity data, current tick in header)
#define TRANSFORM_SNAPSHOT_DELTA_MIN_ARGS_SIZE      (HEADER_SIZE + TRANSFORM_SNAPSHOT_DELTA_BASE_SIZE)  // 26 bytes

// HEALTH_SNAPSHOT_DELTA packet (0x2D)
#define HEALTH_SNAPSHOT_DELTA_BASE_TICK_SIZE        4   // uint32_t
#define HEALTH_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE     2   // uint16_t
#define HEALTH_SNAPSHOT_DELTA_BASE_SIZE             (HEALTH_SNAPSHOT_DELTA_BASE_TICK_SIZE + HEALTH_SNAPSHOT_DELTA_ENTITY_COUNT_SIZE)  // 6 bytes (+ variable entity data, current tick in header)
#define HEALTH_SNAPSHOT_DELTA_MIN_ARGS_SIZE         (HEADER_SIZE + HEALTH_SNAPSHOT_DELTA_BASE_SIZE)  // 26 bytes

// ENTITY_FULL_STATE packet (0x2E)
#define ENTITY_FULL_STATE_ENTITY_ID_SIZE        4   // uint32_t
#define ENTITY_FULL_STATE_ENTITY_TYPE_SIZE      1   // uint8_t
#define ENTITY_FULL_STATE_COMPONENT_COUNT_SIZE  1   // uint8_t
#define ENTITY_FULL_STATE_BASE_SIZE             (ENTITY_FULL_STATE_ENTITY_ID_SIZE + ENTITY_FULL_STATE_ENTITY_TYPE_SIZE + ENTITY_FULL_STATE_COMPONENT_COUNT_SIZE)  // 6 bytes (+ variable component data)
#define ENTITY_FULL_STATE_MIN_ARGS_SIZE         (HEADER_SIZE + ENTITY_FULL_STATE_BASE_SIZE)  // 26 bytes

// ==============================================================
//                    GAME_EVENTS (0x40-0x5F)
// ==============================================================

// PLAYER_HIT packet (0x40)
#define PLAYER_HIT_PLAYER_ID_SIZE               4   // uint32_t
#define PLAYER_HIT_ATTACKER_ID_SIZE             4   // uint32_t
#define PLAYER_HIT_DAMAGE_SIZE                  1   // uint8_t
#define PLAYER_HIT_REMAINING_HEALTH_SIZE        1   // uint8_t
#define PLAYER_HIT_REMAINING_SHIELD_SIZE        1   // uint8_t
#define PLAYER_HIT_HIT_POS_X_SIZE               2   // int16_t
#define PLAYER_HIT_HIT_POS_Y_SIZE               2   // int16_t
#define PLAYER_HIT_PAYLOAD_SIZE                 (PLAYER_HIT_PLAYER_ID_SIZE + PLAYER_HIT_ATTACKER_ID_SIZE + PLAYER_HIT_DAMAGE_SIZE + PLAYER_HIT_REMAINING_HEALTH_SIZE + PLAYER_HIT_REMAINING_SHIELD_SIZE + PLAYER_HIT_HIT_POS_X_SIZE + PLAYER_HIT_HIT_POS_Y_SIZE)  // 15 bytes
#define PLAYER_HIT_MIN_ARGS_SIZE                (HEADER_SIZE + PLAYER_HIT_PAYLOAD_SIZE)  // 35 bytes

// PLAYER_DEATH packet (0x41)
#define PLAYER_DEATH_PLAYER_ID_SIZE             4   // uint32_t
#define PLAYER_DEATH_KILLER_ID_SIZE             4   // uint32_t
#define PLAYER_DEATH_SCORE_BEFORE_DEATH_SIZE    4   // uint32_t
#define PLAYER_DEATH_DEATH_POS_X_SIZE           2   // int16_t
#define PLAYER_DEATH_DEATH_POS_Y_SIZE           2   // int16_t
#define PLAYER_DEATH_PAYLOAD_SIZE               (PLAYER_DEATH_PLAYER_ID_SIZE + PLAYER_DEATH_KILLER_ID_SIZE + PLAYER_DEATH_SCORE_BEFORE_DEATH_SIZE + PLAYER_DEATH_DEATH_POS_X_SIZE + PLAYER_DEATH_DEATH_POS_Y_SIZE)  // 16 bytes
#define PLAYER_DEATH_MIN_ARGS_SIZE              (HEADER_SIZE + PLAYER_DEATH_PAYLOAD_SIZE)  // 36 bytes

// SCORE_UPDATE packet (0x42)
#define SCORE_UPDATE_PLAYER_ID_SIZE             4   // uint32_t
#define SCORE_UPDATE_NEW_SCORE_SIZE             4   // uint32_t
#define SCORE_UPDATE_SCORE_DELTA_SIZE           2   // int16_t
#define SCORE_UPDATE_REASON_SIZE                1   // uint8_t
#define SCORE_UPDATE_PAYLOAD_SIZE               (SCORE_UPDATE_PLAYER_ID_SIZE + SCORE_UPDATE_NEW_SCORE_SIZE + SCORE_UPDATE_SCORE_DELTA_SIZE + SCORE_UPDATE_REASON_SIZE)  // 11 bytes
#define SCORE_UPDATE_MIN_ARGS_SIZE              (HEADER_SIZE + SCORE_UPDATE_PAYLOAD_SIZE)  // 31 bytes

// POWER_PICKUP packet (0x43)
#define POWER_PICKUP_PLAYER_ID_SIZE             4   // uint32_t
#define POWER_PICKUP_POWERUP_ID_SIZE            4   // uint32_t
#define POWER_PICKUP_POWERUP_TYPE_SIZE          1   // uint8_t
#define POWER_PICKUP_DURATION_SIZE              1   // uint8_t
#define POWER_PICKUP_PAYLOAD_SIZE               (POWER_PICKUP_PLAYER_ID_SIZE + POWER_PICKUP_POWERUP_ID_SIZE + POWER_PICKUP_POWERUP_TYPE_SIZE + POWER_PICKUP_DURATION_SIZE)  // 10 bytes
#define POWER_PICKUP_MIN_ARGS_SIZE              (HEADER_SIZE + POWER_PICKUP_PAYLOAD_SIZE)  // 30 bytes

// WEAPON_FIRE packet (0x44)
#define WEAPON_FIRE_SHOOTER_ID_SIZE             4   // uint32_t
#define WEAPON_FIRE_PROJECTILE_ID_SIZE          4   // uint32_t
#define WEAPON_FIRE_ORIGIN_X_SIZE               2   // int16_t
#define WEAPON_FIRE_ORIGIN_Y_SIZE               2   // int16_t
#define WEAPON_FIRE_DIRECTION_X_SIZE            2   // int16_t
#define WEAPON_FIRE_DIRECTION_Y_SIZE            2   // int16_t
#define WEAPON_FIRE_WEAPON_TYPE_SIZE            1   // uint8_t
#define WEAPON_FIRE_PAYLOAD_SIZE                (WEAPON_FIRE_SHOOTER_ID_SIZE + WEAPON_FIRE_PROJECTILE_ID_SIZE + WEAPON_FIRE_ORIGIN_X_SIZE + WEAPON_FIRE_ORIGIN_Y_SIZE + WEAPON_FIRE_DIRECTION_X_SIZE + WEAPON_FIRE_DIRECTION_Y_SIZE + WEAPON_FIRE_WEAPON_TYPE_SIZE)  // 17 bytes
#define WEAPON_FIRE_MIN_ARGS_SIZE               (HEADER_SIZE + WEAPON_FIRE_PAYLOAD_SIZE)  // 37 bytes

// VISUAL_EFFECT packet (0x50)
#define VISUAL_EFFECT_EFFECT_TYPE_SIZE          1   // uint8_t
#define VISUAL_EFFECT_POS_X_SIZE                2   // int16_t
#define VISUAL_EFFECT_POS_Y_SIZE                2   // int16_t
#define VISUAL_EFFECT_DURATION_MS_SIZE          2   // uint16_t
#define VISUAL_EFFECT_SCALE_SIZE                1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_R_SIZE         1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_G_SIZE         1   // uint8_t
#define VISUAL_EFFECT_COLOR_TINT_B_SIZE         1   // uint8_t
#define VISUAL_EFFECT_PAYLOAD_SIZE              (VISUAL_EFFECT_EFFECT_TYPE_SIZE + VISUAL_EFFECT_POS_X_SIZE + VISUAL_EFFECT_POS_Y_SIZE + VISUAL_EFFECT_DURATION_MS_SIZE + VISUAL_EFFECT_SCALE_SIZE + VISUAL_EFFECT_COLOR_TINT_R_SIZE + VISUAL_EFFECT_COLOR_TINT_G_SIZE + VISUAL_EFFECT_COLOR_TINT_B_SIZE)  // 11 bytes
#define VISUAL_EFFECT_MIN_ARGS_SIZE             (HEADER_SIZE + VISUAL_EFFECT_PAYLOAD_SIZE)  // 31 bytes

// AUDIO_EFFECT packet (0x51)
#define AUDIO_EFFECT_EFFECT_TYPE_SIZE           1   // uint8_t
#define AUDIO_EFFECT_POS_X_SIZE                 2   // int16_t
#define AUDIO_EFFECT_POS_Y_SIZE                 2   // int16_t
#define AUDIO_EFFECT_VOLUME_SIZE                1   // uint8_t
#define AUDIO_EFFECT_PITCH_SIZE                 1   // uint8_t
#define AUDIO_EFFECT_PAYLOAD_SIZE               (AUDIO_EFFECT_EFFECT_TYPE_SIZE + AUDIO_EFFECT_POS_X_SIZE + AUDIO_EFFECT_POS_Y_SIZE + AUDIO_EFFECT_VOLUME_SIZE + AUDIO_EFFECT_PITCH_SIZE)  // 7 bytes
#define AUDIO_EFFECT_MIN_ARGS_SIZE              (HEADER_SIZE + AUDIO_EFFECT_PAYLOAD_SIZE)  // 27 bytes

// PARTICLE_SPAWN packet (0x52)
#define PARTICLE_SPAWN_PARTICLE_SYSTEM_ID_SIZE  2   // uint16_t
#define PARTICLE_SPAWN_POS_X_SIZE               2   // int16_t
#define PARTICLE_SPAWN_POS_Y_SIZE               2   // int16_t
#define PARTICLE_SPAWN_VELOCITY_X_SIZE          2   // int16_t
#define PARTICLE_SPAWN_VELOCITY_Y_SIZE          2   // int16_t
#define PARTICLE_SPAWN_PARTICLE_COUNT_SIZE      2   // uint16_t
#define PARTICLE_SPAWN_LIFETIME_MS_SIZE         2   // uint16_t
#define PARTICLE_SPAWN_COLOR_START_R_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_START_G_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_START_B_SIZE       1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_R_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_G_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_COLOR_END_B_SIZE         1   // uint8_t
#define PARTICLE_SPAWN_PAYLOAD_SIZE             (PARTICLE_SPAWN_PARTICLE_SYSTEM_ID_SIZE + PARTICLE_SPAWN_POS_X_SIZE + PARTICLE_SPAWN_POS_Y_SIZE + PARTICLE_SPAWN_VELOCITY_X_SIZE + PARTICLE_SPAWN_VELOCITY_Y_SIZE + PARTICLE_SPAWN_PARTICLE_COUNT_SIZE + PARTICLE_SPAWN_LIFETIME_MS_SIZE + PARTICLE_SPAWN_COLOR_START_R_SIZE + PARTICLE_SPAWN_COLOR_START_G_SIZE + PARTICLE_SPAWN_COLOR_START_B_SIZE + PARTICLE_SPAWN_COLOR_END_R_SIZE + PARTICLE_SPAWN_COLOR_END_G_SIZE + PARTICLE_SPAWN_COLOR_END_B_SIZE)  // 20 bytes
#define PARTICLE_SPAWN_MIN_ARGS_SIZE            (HEADER_SIZE + PARTICLE_SPAWN_PAYLOAD_SIZE)  // 40 bytes

// ==============================================================
//                    GAME_CONTROL (0x60-0x6F)
// ==============================================================

// GAME_START packet (0x60)
#define GAME_START_GAME_INSTANCE_ID_SIZE        4   // uint32_t
#define GAME_START_PLAYER_COUNT_SIZE            1   // uint8_t
#define GAME_START_PLAYER_IDS_SIZE              16  // uint32_t[4]
#define GAME_START_LEVEL_ID_SIZE                1   // uint8_t
#define GAME_START_DIFFICULTY_SIZE              1   // uint8_t
#define GAME_START_PAYLOAD_SIZE                 (GAME_START_GAME_INSTANCE_ID_SIZE + GAME_START_PLAYER_COUNT_SIZE + GAME_START_PLAYER_IDS_SIZE + GAME_START_LEVEL_ID_SIZE + GAME_START_DIFFICULTY_SIZE)  // 23 bytes
#define GAME_START_MIN_ARGS_SIZE                (HEADER_SIZE + GAME_START_PAYLOAD_SIZE)  // 43 bytes

// GAME_END packet (0x61)
#define GAME_END_END_REASON_SIZE                1   // uint8_t
#define GAME_END_FINAL_SCORES_SIZE              16  // uint32_t[4]
#define GAME_END_WINNER_ID_SIZE                 1   // uint8_t
#define GAME_END_PLAY_TIME_SIZE                 4   // uint32_t
#define GAME_END_PAYLOAD_SIZE                   (GAME_END_END_REASON_SIZE + GAME_END_FINAL_SCORES_SIZE + GAME_END_WINNER_ID_SIZE + GAME_END_PLAY_TIME_SIZE)  // 22 bytes
#define GAME_END_MIN_ARGS_SIZE                  (HEADER_SIZE + GAME_END_PAYLOAD_SIZE)  // 42 bytes

// LEVEL_COMPLETE packet (0x62)
#define LEVEL_COMPLETE_COMPLETED_LEVEL_SIZE     1   // uint8_t
#define LEVEL_COMPLETE_NEXT_LEVEL_SIZE          1   // uint8_t
#define LEVEL_COMPLETE_BONUS_SCORE_SIZE         4   // uint32_t
#define LEVEL_COMPLETE_COMPLETION_TIME_SIZE     2   // uint16_t
#define LEVEL_COMPLETE_PAYLOAD_SIZE             (LEVEL_COMPLETE_COMPLETED_LEVEL_SIZE + LEVEL_COMPLETE_NEXT_LEVEL_SIZE + LEVEL_COMPLETE_BONUS_SCORE_SIZE + LEVEL_COMPLETE_COMPLETION_TIME_SIZE)  // 8 bytes
#define LEVEL_COMPLETE_MIN_ARGS_SIZE            (HEADER_SIZE + LEVEL_COMPLETE_PAYLOAD_SIZE)  // 28 bytes

// LEVEL_START packet (0x63)
#define LEVEL_START_LEVEL_ID_SIZE               1   // uint8_t
#define LEVEL_START_LEVEL_NAME_SIZE             32  // char[32]
#define LEVEL_START_ESTIMATED_DURATION_SIZE     2   // uint16_t
#define LEVEL_START_PAYLOAD_SIZE                (LEVEL_START_LEVEL_ID_SIZE + LEVEL_START_LEVEL_NAME_SIZE + LEVEL_START_ESTIMATED_DURATION_SIZE)  // 35 bytes
#define LEVEL_START_MIN_ARGS_SIZE               (HEADER_SIZE + LEVEL_START_PAYLOAD_SIZE)  // 55 bytes

// FORCE_STATE packet (0x64)
#define FORCE_STATE_FORCE_ENTITY_ID_SIZE        4   // uint32_t
#define FORCE_STATE_PARENT_SHIP_ID_SIZE         4   // uint32_t
#define FORCE_STATE_ATTACHMENT_POINT_SIZE       1   // uint8_t
#define FORCE_STATE_POWER_LEVEL_SIZE            1   // uint8_t
#define FORCE_STATE_CHARGE_PERCENTAGE_SIZE      1   // uint8_t
#define FORCE_STATE_IS_FIRING_SIZE              1   // uint8_t
#define FORCE_STATE_PAYLOAD_SIZE                (FORCE_STATE_FORCE_ENTITY_ID_SIZE + FORCE_STATE_PARENT_SHIP_ID_SIZE + FORCE_STATE_ATTACHMENT_POINT_SIZE + FORCE_STATE_POWER_LEVEL_SIZE + FORCE_STATE_CHARGE_PERCENTAGE_SIZE + FORCE_STATE_IS_FIRING_SIZE)  // 12 bytes
#define FORCE_STATE_MIN_ARGS_SIZE               (HEADER_SIZE + FORCE_STATE_PAYLOAD_SIZE)  // 32 bytes

// AI_STATE packet (0x65)
#define AI_STATE_ENTITY_ID_SIZE                 4   // uint32_t
#define AI_STATE_CURRENT_STATE_SIZE             1   // uint8_t
#define AI_STATE_BEHAVIOR_TYPE_SIZE             1   // uint8_t
#define AI_STATE_TARGET_ENTITY_ID_SIZE          4   // uint32_t
#define AI_STATE_WAYPOINT_X_SIZE                2   // int16_t
#define AI_STATE_WAYPOINT_Y_SIZE                2   // int16_t
#define AI_STATE_STATE_TIMER_SIZE               2   // uint16_t
#define AI_STATE_PAYLOAD_SIZE                   (AI_STATE_ENTITY_ID_SIZE + AI_STATE_CURRENT_STATE_SIZE + AI_STATE_BEHAVIOR_TYPE_SIZE + AI_STATE_TARGET_ENTITY_ID_SIZE + AI_STATE_WAYPOINT_X_SIZE + AI_STATE_WAYPOINT_Y_SIZE + AI_STATE_STATE_TIMER_SIZE)  // 18 bytes
#define AI_STATE_MIN_ARGS_SIZE                  (HEADER_SIZE + AI_STATE_PAYLOAD_SIZE)  // 38 bytes

// ==============================================================
//                    PROTOCOL_CONTROL (0x70-0x7F)
// ==============================================================

// ACK packet (0x70)
#define ACK_ACKED_SEQUENCE_SIZE                 4   // uint32_t
#define ACK_RECEIVED_TIMESTAMP_SIZE             4   // uint32_t
#define ACK_PAYLOAD_SIZE                        (ACK_ACKED_SEQUENCE_SIZE + ACK_RECEIVED_TIMESTAMP_SIZE)  // 8 bytes
#define ACK_MIN_ARGS_SIZE                       (HEADER_SIZE + ACK_PAYLOAD_SIZE)  // 28 bytes

// PING packet (0x71)
#define PING_CLIENT_TIMESTAMP_SIZE              4   // uint32_t
#define PING_PAYLOAD_SIZE                       (PING_CLIENT_TIMESTAMP_SIZE)  // 4 bytes
#define PING_MIN_ARGS_SIZE                      (HEADER_SIZE + PING_PAYLOAD_SIZE)  // 24 bytes

// PONG packet (0x72)
#define PONG_CLIENT_TIMESTAMP_SIZE              4   // uint32_t
#define PONG_SERVER_TIMESTAMP_SIZE              4   // uint32_t
#define PONG_PAYLOAD_SIZE                       (PONG_CLIENT_TIMESTAMP_SIZE + PONG_SERVER_TIMESTAMP_SIZE)  // 8 bytes
#define PONG_MIN_ARGS_SIZE                      (HEADER_SIZE + PONG_PAYLOAD_SIZE)  // 28 bytes


// ==============================================================
//                          RENDER WINDOW
// ==============================================================

#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define FRAMERATE_LIMIT 60

// PLAYER
#define PLAYER_SPRITE_WIDTH 33
#define PLAYER_SPRITE_HEIGHT 15
#define PLAYER_SPRITE_SCALE 2.5f

#define PLAYER_ANIMATION_WIDTH 33
#define PLAYER_ANIMATION_HEIGHT 15
#define PLAYER_ANIMATION_CURRENT 2
#define PLAYER_ANIMATION_ELAPSED_TIME 0.f
#define PLAYER_ANIMATION_DURATION 0.1f
#define PLAYER_ANIMATION_START 2
#define PLAYER_ANIMATION_END 2
#define PLAYER_ANIMATION_LOOPING true

#define PLAYER_WEAPON_FIRE_RATE = 200
#define PLAYER_WEAPON_LAST_SHOT = 0
#define PLAYER_WEAPON_DAMAGES = 10
#define PLAYER_WEAPON_TYPE = ProjectileType::MISSILE


// EXPLOSIONS
// SMALL EXPLOSIONS
#define SMALL_EXPLOSION_SPRITE_WIDTH 33
#define SMALL_EXPLOSION_SPRITE_HEIGHT 32
#define SMALL_EXPLOSION_SPRITE_SCALE 2.5f

#define SMALL_EXPLOSION_ANIMATION_WIDTH 33
#define SMALL_EXPLOSION_ANIMATION_HEIGHT 32
#define SMALL_EXPLOSION_ANIMATION_CURRENT 0
#define SMALL_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define SMALL_EXPLOSION_ANIMATION_DURATION 0.1f
#define SMALL_EXPLOSION_ANIMATION_START 0
#define SMALL_EXPLOSION_ANIMATION_END 5
#define SMALL_EXPLOSION_ANIMATION_LOOPING false

// MEDIUM EXPLOSIONS
#define MEDIUM_EXPLOSION_SPRITE_WIDTH 60
#define MEDIUM_EXPLOSION_SPRITE_HEIGHT 52
#define MEDIUM_EXPLOSION_SPRITE_SCALE 2.5f

#define MEDIUM_EXPLOSION_ANIMATION_WIDTH 60
#define MEDIUM_EXPLOSION_ANIMATION_HEIGHT 52
#define MEDIUM_EXPLOSION_ANIMATION_CURRENT 0
#define MEDIUM_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define MEDIUM_EXPLOSION_ANIMATION_DURATION 0.1f
#define MEDIUM_EXPLOSION_ANIMATION_START 0
#define MEDIUM_EXPLOSION_ANIMATION_END 2
#define MEDIUM_EXPLOSION_ANIMATION_LOOPING false

// BIG EXPLOSIONS
#define BIG_EXPLOSION_SPRITE_WIDTH 65
#define BIG_EXPLOSION_SPRITE_HEIGHT 65
#define BIG_EXPLOSION_SPRITE_SCALE 2.5f

#define BIG_EXPLOSION_ANIMATION_WIDTH 65
#define BIG_EXPLOSION_ANIMATION_HEIGHT 65
#define BIG_EXPLOSION_ANIMATION_CURRENT 0
#define BIG_EXPLOSION_ANIMATION_ELAPSED_TIME 0.f
#define BIG_EXPLOSION_ANIMATION_DURATION 0.1f
#define BIG_EXPLOSION_ANIMATION_START 0
#define BIG_EXPLOSION_ANIMATION_END 4
#define BIG_EXPLOSION_ANIMATION_LOOPING false


// PROJECTILES
// BASIC/DEFAULT PROJECTILE
#define DEFAULT_PROJ_ROTATION 0
#define DEFAULT_PROJ_SCALE 2.5f

#define DEFAULT_PROJ_SPRITE_WIDTH 17
#define DEFAULT_PROJ_SPRITE_HEIGHT 12
#define DEFAULT_PROJ_SPRITE_SCALE 2.5f

#define DEFAULT_PROJ_ANIMATION_WIDTH 17
#define DEFAULT_PROJ_ANIMATION_HEIGHT 12
#define DEFAULT_PROJ_ANIMATION_CURRENT 0
#define DEFAULT_PROJ_ANIMATION_ELAPSED_TIME 0.f
#define DEFAULT_PROJ_ANIMATION_DURATION 0.1f
#define DEFAULT_PROJ_ANIMATION_START 0
#define DEFAULT_PROJ_ANIMATION_END 2
#define DEFAULT_PROJ_ANIMATION_LOOPING false


// CHARGED PROJECTILE
#define CHARGED_PROJ_ROTATION 0
#define CHARGED_PROJ_SCALE 2.5f

#define CHARGED_PROJ_SPRITE_WIDTH 81
#define CHARGED_PROJ_SPRITE_HEIGHT 16
#define CHARGED_PROJ_SPRITE_SCALE 2.5f

#define CHARGED_PROJ_ANIMATION_WIDTH 81
#define CHARGED_PROJ_ANIMATION_HEIGHT 16
#define CHARGED_PROJ_ANIMATION_CURRENT 0
#define CHARGED_PROJ_ANIMATION_ELAPSED_TIME 0.f
#define CHARGED_PROJ_ANIMATION_DURATION 0.3f
#define CHARGED_PROJ_ANIMATION_START 0
#define CHARGED_PROJ_ANIMATION_END 1
#define CHARGED_PROJ_ANIMATION_LOOPING true // verify if its better to set to true ou false for this bullets




// UI/HUD
// BUTTONS
// DEFAULT BUTTON
#define DEFAULT_BUTTON_ROTATION 0
#define DEFAULT_BUTTON_SCALE 1.0f

#define DEFAULT_BUTTON_SPRITE_WIDTH 280
#define DEFAULT_BUTTON_SPRITE_HEIGHT 80
#define DEFAULT_BUTTON_SPRITE_SCALE 1.0f


// BACK BUTTON
#define BACK_BUTTON_ROTATION 0
#define BACK_BUTTON_SCALE 1.0f //FIXME: need to be changed I think

#define BACK_BUTTON_SPRITE_WIDTH 22
#define BACK_BUTTON_SPRITE_HEIGHT 20
#define BACK_BUTTON_SPRITE_SCALE 1.0f //FIXME: need to be changed I think


// MUSIC BUTTON
#define MUSIC_BUTTON_ROTATION 0
#define MUSIC_BUTTON_SCALE 1.0f //FIXME: need to be changed I think

#define MUSIC_BUTTON_SPRITE_WIDTH 16
#define MUSIC_BUTTON_SPRITE_HEIGHT 14
#define MUSIC_BUTTON_SPRITE_SCALE 1.0f //FIXME: need to be changed I think

// SOUND BUTTON
#define SOUND_BUTTON_ROTATION 0
#define SOUND_BUTTON_SCALE 1.0f //FIXME: need to be changed I think

#define SOUND_BUTTON_SPRITE_WIDTH 16
#define SOUND_BUTTON_SPRITE_HEIGHT 14
#define SOUND_BUTTON_SPRITE_SCALE 1.0f //FIXME: need to be changed I think


#endif /* !DEFINES_HPP_ */
